### PR TITLE
Feat: Add dockerimage + playwrite headless + auth

### PR DESCRIPTION
**Pull request by stjohn96**
Added auth + headless playwrite to https://github.com/altryne/chatGPT-telegram-bot/pull/18

### CODE REVIEW

**Comment by altryne** [comment]
This is awesome! I have to try it, I'm not in love with adding u/p directly , but this definitely lowers the bar for installing something like this

**Comment by sebaplaza** [comment]
This is great @stjohn96 !

Thanks for adding the auth code, i'm gonna test your branch

**Comment by altryne** [comment]
Thanks for testing @sebaplaza 

@stjohn96 thank you! Could you add a readme entry on this docker? And merge conflicts ? 
I'll merge after

**Comment by sebaplaza** [comment]
@stjohn96 @altryne i resolved merge conflicts in https://github.com/altryne/chatGPT-telegram-bot/pull/18

**Comment by stjohn96** [comment]
@sebaplaza @altryne Im going close this PR in favour of https://github.com/altryne/chatGPT-telegram-bot/pull/18

**Pull request closed without merging**
